### ISSUE TITLE
Elastic Stack v6.x to v7.x Configuration #10

### ISSUE THREAD

**Issue by investlab** [kicker83/ELK-Networking#1]
Dear Kicker83,
I'm using Elastic Stack v7.x. So I can't import your Index template.
Can you help me update this template for Elastic Stack v7.x?
Thankyou!

**Comment by kicker83** [comment]
Hi wisoez,

I duplicated the Elasticsearch templates, one for 6.x and one for 7.x. If you see any json which is not duplicated don't bother about that, because in this case the format is not changing.

Regards!

**Comment by investlab** [comment]
Thankyou very much for quickly support!
